### ISSUE TITLE
Initialization Alastria Name Service

### ISSUE THREAD

**Issue by rober12** [alastria/alastriaID-hardhat-contracts#13]
Error in the Smart Contract Alastria Name Service: Due to the AdminUpgradeabilityProxy of openzeppelin, smart contracts cannot be initialized. This smart contract receives in the constructor a parameter, which is an address of the entity that should be registered as an entity in the smart contract. Since it cannot be initialized, and therefore there is no entity registered in the smart contract, it is unusable because no entity is registered, and the smart contract has a modifier that prevents entities from being registered if the entity is not an entity.

Modifier in the addEntity function:
`function addEntity(address _addressEntity, string memory _name, string memory _cif, string memory _url_logo, string memory _url_createAID, string memory _url_AOA) public notIdentityEntity(_addressEntity) onlyIdentityEntity(msg.sender) {`

Constructor Alastria Name Service
```
 constructor (address _firstIdentity) public{
	    _addEntity(_firstIdentity, name, cif, url_logo, url_createAID, url_AOA, true);
        
    }
```
Script Deploy Name Service:
```
 console.log('DEPLOYING CONTRACTS: NAME SERVICE');
    const alastriaNameServicesSC = await AlastriaNameService.deploy(ADMIN_ADDRESS);
    await alastriaNameServicesSC.deployed();
    const alastriaNameServiceProxy = await Proxy.deploy(alastriaNameServicesSC.address, ADMIN_ADDRESS, []);
    await alastriaNameServiceProxy.deployed();
    console.log('nameServiceDeployed deployed: ', alastriaNameServiceProxy.address);
    await saveAddresesInfo(
      alastriaNameServiceProxy.address,
      config.nameService,
      network
      );
```

Query the smart contract once deployed to check if the smart contract has been initialized correctly.
![image](https://github.com/alastria/alastriaID-hardhat-contracts/assets/17437316/7f55743c-d289-4f93-b75f-04cad0959364)

As can be seen in the image, after the deployment, consulting the address[] listEntities; it can be seen that the address has not been registered, therefore no one can register entities in the smart contract.

For more information on possible solutions visit: https://alastria.atlassian.net/wiki/spaces/ALASTRIAID/pages/699596801/14+06+2024+-+Meeting+Notes+Libs

**Comment by rober12** [comment]
Fix the bug in this pull request -> https://github.com/alastria/alastriaID-hardhat-contracts/pull/14

**Comment by alejandroalffer** [comment]
Great job @rober12 && @DaniRumpi !
